#!/bin/bash

function gitpkg () {
    mkdir -p ~/.vim/pack/plugins/start/
    cd ~/.vim/pack/plugins/start/
    git clone $1
}

gitpkg git@github.com:vim-airline/vim-airline.git
gitpkg git@github.com:tpope/vim-fugitive.git
gitpkg git@github.com:mhinz/vim-signify.git
gitpkg git@github.com:leafo/moonscript-vim.git
